### PR TITLE
rgw_sal_motr: [CORTX-34181] allow multiparts with offline server

### LINKED ISSUE #422: Multi-part uploads fail when some server is offline
Currently, we create an additional index for each multipart uploaded object to store its parts. If some server is down, the index creation operation would fail, thus failing the multipart upload.

So we should avoid creating indexes on multipart uploads. It's not only a heavyweight operation in motr, but also not fault-tolerant atm ([to be fixed in motr](https://github.com/Seagate/cortx-motr/issues/2142) later). For example, when we create a bucket, in addition to the bucket-index we can create a bucket-mp-index to store the objects' parts.

### PR DESCRIPTION
**Pull request by andriytk**
Currently, we create an additional index for each multipart-uploaded object to store its parts. If some server is down, the index creation operation would fail, thus failing the multipart upload.

Solution: don't create indexes on multipart uploads. Create an additional index to store objs parts when the bucket is created.

Closes #422.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

File: src/rgw/rgw_sal_motr.cc [hunk 1]
```diff
@@ -2228,14 +2247,12 @@ int MotrObject::remove_mobj_and_index_entry(
...
-                                       this->get_name() + "." + upload_id +
-                                       ".parts";
-          ldpp_dout(dpp, 20) << __func__ << ": object part index=" << obj_part_iname << dendl;
+          std::string obj_fqdn = delete_key + "." + upload_id;
+          std::string iname = "motr.rgw.bucket." + bucket_name + ".multiparts";
+          ldpp_dout(dpp, 20) << __func__ << ": object part index=" << iname << dendl;
           ::Meta *mobj = reinterpret_cast<::Meta*>(&this->meta);
           motr_gc_obj_info gc_obj(upload_id, obj_fqdn, *mobj, std::time(nullptr),
-                                ent.meta.size, true, obj_part_iname);
+                                ent.meta.size, true, iname);
```
Comment (siningwuseagate) [inline src/rgw/rgw_sal_motr.cc:2255]: If I understand it correctly, MotrObject::MotrDeleteOp::create_delete_marker() is called when deleting an object, the code here seems to put the 'bucket' part index into gc queue every time a bucket's object is deleted, shouldn't the index be removed at MotrBucket::remove_bucket()?

Comment (jjxsg) [reply src/rgw/rgw_sal_motr.cc:2255]: It is putting part index in GC so that GC can distribute the parts in available GC queues for deletion. Earlier we were deleting this index once all parts are deleted, but with these code changes, we will retain this index until delete bucket op in called.

Comment (siningwuseagate) [reply src/rgw/rgw_sal_motr.cc:2255]: i c, thanks, I mis-understood the code and thought it is to put the index into the gc queue.

File: src/rgw/rgw_sal_motr.cc [hunk 2]
```diff
@@ -4608,21 +4605,20 @@ int MotrMultipartWriter::complete(size_t accounted_size, const std::string& etag
   encode(attrs, bl);
   part_obj->meta.encode(bl);
 
-  string p = "part.";
-  char buf[32];
-  snprintf(buf, sizeof(buf), "%08d", (int)part_num);
-  p.append(buf);
-  string tenant_bkt_name = get_bucket_name(head_obj->get_bucket()->get_tenant(), head_obj->get_bucket()->get_name());
```
Comment (jjxsg) [inline src/rgw/rgw_sal_motr.cc:4615]: `tenant_bkt_name` is required by `update_bucket_stats()` called later in the function.

File: src/rgw/motr/gc/gc.cc [hunk 3]
```diff
@@ -263,6 +263,7 @@ int MotrGC::process_parts(motr_gc_obj_info ginfo, std::time_t end_time) {
   std::vector<std::string> keys(max_entries);
   std::vector<bufferlist> vals(max_entries);
 
+  keys[0] = name;
```
Comment (jjxsg) [inline src/rgw/motr/gc/gc.cc:266]: should be `ginfo.name`

File: src/rgw/rgw_sal_motr.cc (hunk 1 above)
Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:2255]: That's correct. Thank you, @jjxsg, for replying to this.

File: src/rgw/motr/gc/gc.cc (hunk 3 above)
Comment (andriytk) [reply src/rgw/motr/gc/gc.cc]: Fixed, thanks!

File: src/rgw/rgw_sal_motr.cc (hunk 2 above)
Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:4615]: Fixed. Thanks!

File: src/rgw/rgw_sal_motr.cc [hunk 4]
```diff
@@ -2228,14 +2247,12 @@ int MotrObject::remove_mobj_and_index_entry(
         if (rc < 0) {
           ldpp_dout(dpp, 0) <<__func__<< ": ERROR: get_upload_id failed. rc=" << rc << dendl;
         } else {
-          std::string obj_fqdn = bucket_name + "/" + delete_key;
-          std::string obj_part_iname = "motr.rgw.object." + bucket_name + "." +
-                                       this->get_name() + "." + upload_id +
-                                       ".parts";
-          ldpp_dout(dpp, 20) << __func__ << ": object part index=" << obj_part_iname << dendl;
+          std::string obj_fqdn = delete_key + "." + upload_id;
```
Comment (sumedhak27) [inline src/rgw/rgw_sal_motr.cc:2250]: While writing parts we don't have version_id generated, it is generated in the complete stage.
thus here delete_key will be  `obj_name + "\a" + version_id` (id is generated), 
but in upload part i.e. MultipartWriter::complete  key will be   `obj_name`.
```suggestion
          std::string obj_fqdn = this->get_name() + "." + upload_id;
```

File: src/rgw/rgw_sal_motr.cc [hunk 5]
```diff
@@ -4608,21 +4605,19 @@ int MotrMultipartWriter::complete(size_t accounted_size, const std::string& etag
...
-  char buf[32];
-  snprintf(buf, sizeof(buf), "%08d", (int)part_num);
-  p.append(buf);
-  string tenant_bkt_name = get_bucket_name(head_obj->get_bucket()->get_tenant(), head_obj->get_bucket()->get_name());
   //This is a MultipartComplete operation so this should always have valid upload id.
-  string upload_id_str = upload_id;
-  string obj_part_iname = "motr.rgw.object." + tenant_bkt_name + "." +
-	                  head_obj->get_key().to_str() + "." + upload_id_str + ".parts";
-  ldpp_dout(dpp, 20) <<__func__ << ": object part index=" << obj_part_iname << dendl;
+  string part = head_obj->get_key().to_str() + "." + upload_id;
```
Comment (sumedhak27) [inline src/rgw/rgw_sal_motr.cc:4609]: `get_key.to_str()` will in this case return `obj_name` since version_id is not yet generated, but in case version_id is present it will return `obj_name[version_id]`. _(this will never happen but function suggests we want such formatting)_
also we should not use `get_key().to_str()` as we have `get_key_str()` which has different structure i.e `obj1[v1] vs obj1^Gv1`
```suggestion
  string part = head_obj->get_name() + "." + upload_id;
```

File: src/rgw/rgw_sal_motr.cc (hunk 4 above)
Comment (sumedhak27) [reply src/rgw/rgw_sal_motr.cc:2250]: **JFYI**
Now @sachinpunadikar , @jjxsg the meaning/use of ginfo.name is different for multipart and simple obj.
**for multipart:**  we are using it to search obj parts in the bucket_parts_index_table and it does have a bucket name in it
**for simple:**  we are not using it at all, it is only for information and it contains the bucket name.

Comment (jjxsg) [reply src/rgw/rgw_sal_motr.cc:2250]: @sumedhak27 `ginfo.name` is important for listing GC entries irrespective of type of object.

File: src/rgw/motr/gc/gc.h [hunk 6]
```diff
@@ -81,10 +81,10 @@ struct motr_gc_obj_info {
   motr_gc_obj_info() {}
   motr_gc_obj_info(const std::string& _tag, const std::string& _name, Meta& _mobj,
                    const std::time_t& _deletion_time, const std::uint64_t& _size,
-                   bool _is_multipart, const std::string& _multipart_iname)
-      : tag(_tag), name(_name), mobj(_mobj),
-        deletion_time(_deletion_time), size(_size),
-        is_multipart(_is_multipart), multipart_iname(_multipart_iname) {}
+                   const std::string& _multipart_iname="")
+      : tag(_tag), name(_name), mobj(_mobj), deletion_time(_deletion_time),
+        size(_size), is_multipart(_multipart_iname != "" ? true : false),
```
Comment (sumedhak27) [inline src/rgw/motr/gc/gc.h:86]: **cosmetic (unimportant)**
```suggestion
        size(_size), is_multipart(_multipart_iname != ""),
        //  OR 
        size(_size), is_multipart(!_multipart_iname.empty()),
```

File: src/rgw/rgw_sal_motr.cc (hunk 4 above)
Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc]: @sumedhak27, good catch. Thanks!

File: src/rgw/rgw_sal_motr.cc (hunk 5 above)
Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc]: Very good catch. Changed to `get_key_str()` here and in several other places. Please check. Thanks!

Comment (sumedhak27) [reply src/rgw/rgw_sal_motr.cc]: No no, we will ned `get->name()` mostly.
The problem is, in `part_upload` i.e. in `MotrMultipartWriter::complete()`, we don't have the version_id set yet, so `get_key_str()` will return `obj_name + '\a'`.
But After `MotrMultipartUpload::complete()` we will have version_id stored in the metadata, so in delete flow i.e in `remove_mobj_and_index_entry()`, `get_key_str()` will return `obj_name + '\a' + version_id`.

Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc]: Right, I realised this by myself also. Fixed again to `->get_name()`. Thanks!

**Review by jjxsg — APPROVED** [review]

**Comment by andriytk** [comment]
Run a smoke tests manually on my devvm setup (writing/reading/checking multipart uploaded object) with and without caching enabled - it seems working fine.

**Comment by sachitanands** [comment]
Hi @andriytk Could you please run Sanity ceph test suite with your PR. 
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/  

this is to make sure existing tests are not breaking.

**Review by sumedhak27 — APPROVED** [review]

**Comment by andriytk** [comment]
Started https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/248/

**Comment by andriytk** [comment]
test_multipart_upload_multiple_sizes has failed, trying to figure out the problem...

**Comment by andriytk** [comment]
Reproduced:
```
$ aws s3 cp --endpoint-url http://localhost:8000 /tmp/10m+100k s3://testbucket0/10m+100k
upload failed: ../../tmp/10m+100k to s3://testbucket0/10m+100k An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: Unknown
```

File: src/rgw/rgw_sal_motr.cc [hunk 7]
```diff
@@ -4187,15 +4183,14 @@ int MotrMultipartUpload::list_parts(const DoutPrefixProvider *dpp, CephContext *
...
+  ldpp_dout(dpp, 20) <<__func__ << ": object part index=" << iname << dendl;
   key_vec[0].clear();
-  key_vec[0] = "part.";
+  key_vec[0] = mp_obj.get_key() + "." + upload_id;
   char buf[32];
-  snprintf(buf, sizeof(buf), "%08d", marker + 1);
+  snprintf(buf, sizeof(buf), ".%08d", marker + 1);
   key_vec[0].append(buf);
-  rc = store->next_query_by_name(obj_part_iname, key_vec, val_vec);
+  rc = store->next_query_by_name(iname, key_vec, val_vec);
```
Comment (DPG17) [inline src/rgw/rgw_sal_motr.cc:4193]: @andriytk : As this Motr's next_KV operation can return parts of some other multipart upload (due to the fact that now parts of different multipart sessions are stored in the same index), we would need a logic in this list_parts function to discard those parts that belong to some other multipart upload (i.e. with different upload_id) and stop further enumeration, so that list_parts returns only the parts of the given upload id.

Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:4193]: Very true, will add it. Thanks, @DPG17!

Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc]: Fixed. @DPG17, please check.

**Comment by andriytk** [comment]
retest this please

**Comment by andriytk** [comment]
retest this please

**Review by siningwuseagate — APPROVED** [review]

**Comment by andriytk** [comment]
retest this please

**Comment by andriytk** [comment]
Started https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/251/

**Comment by andriytk** [comment]
image
