### PR TITLE
rgw_sal_motr: [CORTX-32326] fix redundant mdata i/o

### LINKED ISSUE #311: Many redundant motr-dix-GETs on object write
When writing a new object, we are trying to GET its old metadata from Motr several times:

```
2022-06-17T14:52:08.865+0000 7fa3c63c5700 20 req 11752172841334917777 6.937022686s s3:put_obj complete: key=200m-3[zWqyGzuQHfbf.RdMTJ11q52mShB05em], meta:oid=[0x71d10c5:0x7bba000000f00001], meta:pvid=[0x7600000000000001:0x0], meta:layout_id=0xb etag=2e03be48531fa1ee59885d67f40e72bd user_data=0
2022-06-17T14:52:08.865+0000 7fa3c63c5700  0 req 11752172841334917777 6.937022686s s3:put_obj Cache miss: name = 200m-3^null, rc = -2
2022-06-17T14:52:08.865+0000 7fa3c63c5700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.865+0000 7fa3c63c5700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.865+0000 7fa3c63c5700 20 do_idx_op_by_name: op=GET idx=motr.rgw.bucket.index.test-bucket key=200m-3^null
2022-06-17T14:52:08.882+0000 7fa3c63c5700  0 do_idx_op: ERROR: idx op failed: -2
2022-06-17T14:52:08.882+0000 7fa3c63c5700  0 do_idx_op_by_name: ERROR: index operation 15 failed, rc = -2
2022-06-17T14:52:08.882+0000 7fa3c63c5700 20 req 11752172841334917777 6.954022408s s3:put_obj fetch_null_obj_reference:  GET null index entry 200m-3^null, rc = -2
2022-06-17T14:52:08.882+0000 7fa3c63c5700 20 req 11752172841334917777 6.954022408s s3:put_obj fetch_null_obj: Null reference index entry is not present in the bucket.
2022-06-17T14:52:08.882+0000 7fa3c63c5700  0 req 11752172841334917777 6.954022408s s3:put_obj Cache miss: name = 200m-3^null, rc = -2
2022-06-17T14:52:08.882+0000 7fa3c63c5700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.882+0000 7fa3c63c5700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.882+0000 7fa3c63c5700 20 do_idx_op_by_name: op=GET idx=motr.rgw.bucket.index.test-bucket key=200m-3^null
2022-06-17T14:52:08.889+0000 7fa3c63c5700  0 do_idx_op: ERROR: idx op failed: -2
2022-06-17T14:52:08.889+0000 7fa3c63c5700  0 do_idx_op_by_name: ERROR: index operation 15 failed, rc = -2
2022-06-17T14:52:08.890+0000 7fa3c63c5700 20 req 11752172841334917777 6.962022305s s3:put_obj fetch_null_obj_reference:  GET null index entry 200m-3^null, rc = -2
2022-06-17T14:52:08.890+0000 7fa3c63c5700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.890+0000 7fa3c63c5700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T14:52:08.890+0000 7fa3c63c5700 20 do_idx_op_by_name: op=PUT idx=motr.rgw.bucket.index.test-bucket key=200m-3^null
2022-06-17T14:52:08.917+0000 7fa3c63c5700 20 req 11752172841334917777 6.989022255s s3:put_obj update_null_reference: Update null version index key, rc : 0
```

And when overwriting an existing object, we are doing metadata GET **three times**!:

```
2022-06-17T15:14:00.492+0000 7f3fb0a9e700 20 req 6575134653163292256 4.784001350s s3:put_obj complete: key=200m-3[zWqyBUh9PZ6bWEql4rCZ0gHOIl.wWMz], meta:oid=[0x5f810c5:0x7bc2000001100000], meta:pvid=[0x7600000000000001:0x0], meta:layout_id=0xb etag=2e03be48531fa1ee59885d67f40e72bd user_data=0
2022-06-17T15:14:00.492+0000 7f3fb0a9e700  0 req 6575134653163292256 4.784001350s s3:put_obj Cache miss: name = 200m-3^null, rc = -2
2022-06-17T15:14:00.492+0000 7f3fb0a9e700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.492+0000 7f3fb0a9e700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.492+0000 7f3fb0a9e700 20 do_idx_op_by_name: op=GET idx=motr.rgw.bucket.index.test-bucket key=200m-3^null
2022-06-17T15:14:00.499+0000 7f3fb0a9e700 20 req 6575134653163292256 4.791001797s s3:put_obj fetch_null_obj_reference:  GET null index entry 200m-3^null, rc = 0
2022-06-17T15:14:00.499+0000 7f3fb0a9e700  0 req 6575134653163292256 4.791001797s s3:put_obj Cache miss: name = 200m-3[zWqyGzuQHfbf.RdMTJ11q52mShB05em], rc = -2
2022-06-17T15:14:00.499+0000 7f3fb0a9e700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.499+0000 7f3fb0a9e700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.499+0000 7f3fb0a9e700 20 do_idx_op_by_name: op=GET idx=motr.rgw.bucket.index.test-bucket key=200m-3[zWqyGzuQHfbf.RdMTJ11q52mShB05em]
2022-06-17T15:14:00.517+0000 7f3fb0a9e700  0 req 6575134653163292256 4.809001923s s3:put_obj Put into cache: name = 200m-3[zWqyGzuQHfbf.RdMTJ11q52mShB05em]
2022-06-17T15:14:00.517+0000 7f3fb0a9e700  0 req 6575134653163292256 4.809001923s s3:put_obj Cache miss: name = 200m-3^null, rc = -2
2022-06-17T15:14:00.517+0000 7f3fb0a9e700 20 index_name_to_motr_fid: id = 0xac2782f2e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.517+0000 7f3fb0a9e700 20 index_name_to_motr_fid: converted id = 0x78000000e8b5bacc:0xeb2ec812d43555d8
2022-06-17T15:14:00.517+0000 7f3fb0a9e700 20 do_idx_op_by_name: op=GET idx=motr.rgw.bucket.index.test-bucket key=200m-3^null
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj fetch_null_obj_reference:  GET null index entry 200m-3^null, rc = 0
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj overwrite_null_obj: Old simple object exists
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj open_mobj: key=200m-3[null], meta:oid=[0x71d10c5:0x7bba000000f00001]
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj open_mobj: key=200m-3[null], meta:oid=[0x71d10c5:0x7bba000000f00001], meta:pvid=[0x7600000000000001:0x0], meta:layout_id=0xb
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj open_mobj: exit. rc =0
2022-06-17T15:14:00.525+0000 7f3fb0a9e700 20 req 6575134653163292256 4.817001820s s3:put_obj delete_mobj: deleting motr object oid=71d10c5:7bba000000f00001
```

This is crazy, really. Why are we doing it?

### PR DESCRIPTION
**Pull request by andriytk**
When writing an object we are getting object's metadata
several times: sometimes two, sometimes even three times,
when there is no real need. This generates a lot of
redundant fops in the network and redundant load on the
servers.

The need of sending several GET requests comes from the
concept of using null-reference entry, which references
the real null entry in the metadata records: we get the
null reference entry first, read the reference key from
it (the key-instance hash), and then we get the real null
entry by using the key name and its instance hash.

Solution: refactor & simplify the code: 1) don't store
the key instance hash for the null entries, there is no
real need for this; this allows to 2) get rid of the null
reference entry concept entirely.

Testing: tested put, get, delete simple and multipart
objects on unversioned, versioned and suspended buckets.

Closes #311.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

File: src/rgw/rgw_sal_motr.cc [hunk 1]
```diff
@@ -1525,26 +1518,17 @@ MotrObject::~MotrObject() {
...
+
   if (rc < 0) {
       ldpp_dout(dpp, 0) <<__func__<< ": ERROR: failed to get object entry. rc=" << rc << dendl;
       return rc;
-    }
-
-  read_bucket_info(dpp, bname, key, target_obj);
-
-  // getting key for version cases
-  if(ent.key.instance == "null")
```
Comment (shriya-deshmukh) [inline src/rgw/rgw_sal_motr.cc:1536]: @andriytk  Could you please explain why do we need to remove this code?
This code is required to support versioning. Also seen simillar changes in this PR.

Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:1536]: The versioning works without this code, see explanation in the description above. Please let me know if it's not so, and what exactly does not work.

Comment (shriya-deshmukh) [reply src/rgw/rgw_sal_motr.cc:1536]: We did some sanity testing for this patch and below are the list of scenario that might not work.

list-object-versions API:
- Null versions always listed at the top in the list-object-versions API response.
 
get-object API:
- get-object API might not work with --version-id null parameter for simple and multipart object
Expected o/p: object data for actual null version should be return.

head-object API:
- Head-object API might not work with --version-id null parameter for simple and multipart object.
Expected o/p: object metadata for actual null version should be return.
 
delete-object API:
- In suspended bucket delete-object api might not work with --version-id null parameter.
Expected o/p: It should delete null version.
 
- In case of suspended bucket, there might be a chances to have two null versions present in the bucket, one is null delete-marker and null version object.
Expected o/p: only one null entry should be present in the bucket - delete-marker/null version.

Comment (shriya-deshmukh) [reply src/rgw/rgw_sal_motr.cc:1536]: Above scenarios are already listed in this doc -https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1036157829/Test+scenarios+for+overall+versioning+feature

File: src/rgw/rgw_sal_motr.cc [hunk 2]
```diff
@@ -1770,20 +1754,11 @@ int MotrObject::MotrReadOp::prepare(optional_yield y, const DoutPrefixProvider*
...
-  {
-    rc = -ENOENT;
-    return rc;
-  }
   if (rc < 0)
     return rc;
 
-  // In case of un-versioned/suspended case,
-  // GET and HEAD object output should ignore versiodId field.
-  if (!source->have_instance()) {
```
Comment (sachitanands) [inline src/rgw/rgw_sal_motr.cc:1783]: Hi @andriytk  we added this check for making MGW behavior inline with AWS & RADOS
short problem description: In case of null version object, GET/HEAD object should not display version-id field in response..
 Only case is when end user pass "--version-id null " as request parameters then only we should display null version-id as part of response.
 
please refer this JIRA : https://jts.seagate.com/browse/CORTX-31876

Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:1783]: It doesn't show it:

```
$ aws s3api get-object --endpoint-url http://localhost:8000 --bucket testbucket --key 8m /tmp/8m.check 
{
    "AcceptRanges": "bytes",
    "LastModified": "Mon, 20 Jun 2022 13:28:08 GMT",
    "ContentLength": 8388608,
    "ETag": "\"9da99fe0893981324aec37836e1f21cf\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
$ aws s3api head-object --endpoint-url http://localhost:8000 --bucket testbucket --key 8m 
{
    "AcceptRanges": "bytes",
    "LastModified": "Mon, 20 Jun 2022 13:28:08 GMT",
    "ContentLength": 8388608,
    "ETag": "\"9da99fe0893981324aec37836e1f21cf\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

File: src/rgw/rgw_sal_motr.cc (hunk 1 above)
Comment (andriytk) [reply src/rgw/rgw_sal_motr.cc:1536]: Thanks. Please check the latest code - it should work now.

**Comment by andriytk** [comment]
Build version - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6854/

**Comment by andriytk** [comment]
Build version - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6855/

**Comment by andriytk** [comment]
Build version - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6860/

**Review by priyanka25081999 — APPROVED** [review]
Thanks @andriytk for the patch. Looks good to me.
